# .github/workflows/reusable-workflow.yml
name: Reusable Workflow

on:
  workflow_call:
    inputs:
      example-input:
        description: 'An example input'
        required: true
        type: string
    secrets:
      example-secret:
        description: 'An example secret'
        required: true

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "Input value is ${{ inputs.example-input }}"
