# .github/workflows/split-reusable-workflow.yml
name: Split Reusable Workflow

on:
  workflow_call:

jobs:
  # Split whole table data file to small record data file (record data file is modified, repo is dirty now)
  split-table:
    name: Split table to records
    runs-on: ubuntu-latest

    # concurrency:
    #   group: split
    #   cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # `git diff-tree` (used in `@db-man/cli splitUpdatedTables`) need to compare HEAD and HEAD~1, so need to fetch 2 commits

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # Split updated table files (by SHA) to the record files
      # Only tables which has updated table data files will be split
      - name: Split table data file
        run: npx @db-man/cli splitUpdatedTables $GITHUB_SHA

      # Debug: check which record files are modified
      - name: git status
        run: |
          git status
          git diff
          git pull # this will make sure local update to date

      - name: Commit files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git status
          git add .
          git status
          git commit -m "[CI] Split table to records"

      - name: Push changes
        uses: ad-m/github-push-action@master
        # when multiple jobs run at the same time, only last git push will sucess, then other pipelines will fail and send email.
        # to prevent get lots of email notification, use `continue-on-error` to make pipeline success even the git push failed.
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
