name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      # Build this package first, because it's a dependency of @db-man/components
      - name: Build @db-man/github
        run: npm run build -w packages/github

      - name: Run tests
        run: |
          ls node_modules/@db-man/github
          ls packages/github/dist
          ls packages/github/es6
          npm test
