name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check lerna version
        run: lerna --version

      # - name: Checkout repository
      #   uses: actions/checkout@v2

      # - name: Setup Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: '16'

      # - name: Install dependencies
      #   run: lerna --version; npx lerna@4 bootstrap
